-- =====================================================
-- One Clickz Viewer - Migration 023: PCPNDT Form F
-- Plain idempotent SQL for the PHP migration runner.
-- =====================================================

CREATE TABLE IF NOT EXISTS `pcpndt_form_f` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `study_uid` VARCHAR(128) DEFAULT NULL,
  `order_id` INT(11) UNSIGNED DEFAULT NULL,
  `visit_id` INT(11) UNSIGNED DEFAULT NULL,
  `patient_id` INT(11) UNSIGNED DEFAULT NULL,
  `examination_id` INT(11) UNSIGNED DEFAULT NULL,
  `status` ENUM('draft','generated','printed','submitted','failed') NOT NULL DEFAULT 'draft',
  `created_by` INT(11) UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pcpndt_portal_credentials` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state_code` VARCHAR(20) NOT NULL,
  `username` VARCHAR(120) DEFAULT NULL,
  `password_enc` TEXT DEFAULT NULL,
  `extra` JSON DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_pcpndt_state` (`state_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `pcpndt_form_f`
  ADD COLUMN IF NOT EXISTS `study_uid` VARCHAR(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `order_id` INT(11) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `visit_id` INT(11) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `patient_id` INT(11) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `examination_id` INT(11) UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ref_no` VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `clinic_name` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `clinic_registration_no` VARCHAR(80) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `clinic_address` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `patient_name` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `patient_age` VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `husband_or_father_name` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `full_address` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `phone` VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `id_proof_type` VARCHAR(60) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `id_proof_number` VARCHAR(80) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `num_living_children` VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `children_details` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `referring_doctor` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `referring_doctor_address` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `referring_doctor_reg_no` VARCHAR(80) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `lmp_date` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `gestational_age` VARCHAR(40) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `edd` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `family_history` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `basis_of_diagnosis` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `indications` JSON DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `procedure_type` VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `procedures` JSON DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `procedure_date` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `complications` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `result` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `result_conveyed` VARCHAR(8) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `performing_doctor` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `performing_doctor_qualification` VARCHAR(120) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `performing_doctor_reg_no` VARCHAR(80) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `declaration_text` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `pdf_path` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `portal_ack_no` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `submitted_at` DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `submitted_by` INT(11) UNSIGNED DEFAULT NULL;

ALTER TABLE `pcpndt_form_f`
  MODIFY COLUMN `order_id` INT(11) UNSIGNED NULL;

ALTER TABLE `pcpndt_form_f`
  ADD UNIQUE INDEX IF NOT EXISTS `uq_pcpndt_study` (`study_uid`);

INSERT INTO `hospital_settings` (`setting_key`, `setting_value`, `setting_group`) VALUES
  ('pcpndt_registration_no', '', 'pcpndt'),
  ('clinic_state', 'maharashtra', 'pcpndt')
ON DUPLICATE KEY UPDATE `setting_key` = `setting_key`;
